index.html

Just smashed out a basic data file implementation.
Let's start jamming tools in there gung ho! Then we can worry about what extra bits of information we might like to add, and worry about how to _get_ that data.

Jekyll data files are cool

---

_data/tools.yml

As full disclosure, I'm part of that project.

Add generator-openapi-repo to code-generators

---

api/categories.json
api/tools.json

Provides the following endpoints
* /api/categories.json
* /api/tools.json
so people can remix the data, create funky front-ends etc.

idea; faux api support

---

_data/tools.yml

Add description and license for KaiZen-OpenAPI-Editor

---

_data/tools.yml

Signed-off-by: Eric Wittmann <eric.wittmann@gmail.com>

Updated the spec version capabilities of Apicurio.

---

_data/tools.yml

Added [Senya](https://senya.io), a Swagger 2.0 and OpenAPI 3.0 editor for JetBrains IDEs.
[https://plugins.jetbrains.com/plugin/10690-senya-editor](https://plugins.jetbrains.com/plugin/10690-senya-editor)

Added Senya Editor to tools.yaml

---

_data/categories.yml
_data/tools.yml

Please find the following changes in this pull request - 
- Added a new **Testing** category
- Added Swagger Inspector under Testing
- Moved Swagger Codegen to **SDK Generators** category from **Documentation** category
- Added SwaggerHub to **Editor** category

Added a new category and tools

---

_data/tools.yml

The addition of this resource was initially requested here: https://github.com/akorchev/odata2openapi/issues/27

Add converter odata2openapi.

---

_data/tools.yml

(PR#39 follow-up) ...and here is another one, Dredd, by the makers of Apiary. Great tool to use in API-first scenarios.

Add Dredd in testing/parsers

---

_data/tools.yml

add stoplight

---

_data/categories.yml
_data/tools.yml

Solves #53 
I haven't used some of the tools like RepreZen Api Studio so please double check whether the categories are actually correct.

Split text and gui editors into separate categories

---

_data/tools.yml

Hi!
Here's a new module I've just released on NPM. Would you consider adding this to your list? 
Github: https://github.com/anttiviljami/openapi-backend
NPM: https://www.npmjs.com/package/openapi-backend
Thanks in advance for your feedback!

Add openapi-backend node.js module

---

_data/tools.yml

Thanks for the quick merge! Sorry I missed the GitHub links - added here.

Add GitHub links

---

_data/tools.yml

Let me know if I need to tweak anything!

add Spectral

---

_data/tools.yml

Added MrinDoc to the list of API Docs

---

_data/tools.yml

Reverts apisyouwonthate/openapi.tools#67

Revert "Add api2html"

---

_data/tools.yml

Thanks for collecting these tools all in one place!

Adding guardrail

---

_data/tools.yml

[RapiDoc Documentation](https://mrin9.github.io/RapiDoc/)

Added RapiDoc a Custom-Element for Open API spec View

---

_data/tools.yml

Disclaimer — I am the founder of [bump.sh](https://bump.sh).

Add bump.sh reference in the Documentation category

---

_data/tools.yml

Stoplight has v3 support for raw editing & documentation, but not GUI editing (yet).

Show v3 as under construction for Stoplight

---

_data/tools.yml

place Stoplight progress link in right place

---

_data/tools.yml

Appears to be dead: https://rapidodesigner.com/

remove Rápido

---

_data/tools.yml

https://github.com/anbuksv/avantation

Add avantation

---

README.md

This site use jekyll but not everyone know it.
So I add contribute process.
But I don't know how to update real site...
I checked few closed pull-request, they don't commit html file.
So we don't need update html ?

add how to contribute section

---

_data/tools.yml

The [committee](https://github.com/interagent/committee) gem is validation middleware for Rack.
This gem support OpenAPI 2 and 3 validation.

add committee gem

---

_data/tools.yml

Hi ! We appreciate your initiative and would like to propose our open source framework (Api Platform) to the server implementations.

Add Api Platform to the server implementations

---

_data/tools.yml

[RapiPdf](https://mrin9.github.io/RapiPdf) - A PDF generator from the Spec

Added RapiPdf under documentation category

---

_data/tools.yml

It does provide schema validation, but no data validation.

fix category for cebe/php-openapi

---

_data/tools.yml

MicroTS generates TypeScript server code form OpenAPI schema. Server validates the input and offers Swagger-UI user interface.
Description of the tool: https://github.com/tomi-vanek/microts#readme

Added MicroTS code generator

---

_data/tools.yml

Update prism v3 status

---

_data/tools.yml

Adding a new VS Code plugin that has not been listed yet

Add VSCode plugin

---

_data/tools.yml

Please add to GUI Editors section as proposed.  Let me know if you have any question

Hackolade visual editor

---

_data/tools.yml

Openapi -> OpenAPI
OpenApi -> OpenAPI
Open API -> OpenAPI

Fixed case for OpenAPI

---

_data/tools.yml

Specs, Definitions, ... -> API Description
https://www.apisyouwonthate.com/blog/resolving-overloaded-terms-for-api-specifications-descriptions-contract

API Descriptions

---

_data/tools.yml

Add link for Vert.x Web API Service (Different from Web API Contract)

Added Vert.x Web API Service

---

_data/tools.yml

feat: added @nll/api-codegen-ts to data-validators and sdk categories

---

index.html

Wow, I blinked and there are loads of great tools listed here! However now I can't find my way around the list because it is so long, and I wanted to link to a specific type of tool from a blog post. So I have added anchors to all the category headings and a little Table of Contents at the top. Hope you like it :)

Add some simple section navigation

---

_data/tools.yml

(plus some minor formatting fixes)

Add express-openapi-validator

---

_data/tools.yml

rename swagger to openapi

---

_data/tools.yml

Apitive Studio is a  platform for Digital Product Managers and API Consultants to design REST APIs. 
The previous pull request was closed due to the marketing page/website not mentioning OpenAPI. This has now been corrected.

Added details of Apitive Studio

---

_data/tools.yml

Specification parser with validation.
OpenAPI Operation validation (i.e. requests and responses).
Provides server adapters for direct plugin (Vert.x (w/ router factory), Undertow and servlet).
This project aims to finally provide a complete and consistent solution to validate API inputs/outputs for Jakarta projects.
https://github.com/openapi4j/openapi4j

Add openapi4j

---

_data/tools.yml

Add vyuldashev/laravel-openapi to list of documentation tools. The tool will help to generate OpenAPI specification for Laravel applications.

Add vyuldashev/laravel-openapi mention

---

_data/categories.yml
_data/tools.yml

- Added Optic
- Added Swagger Inspector 
-- removed --
Generate OAS (deprecated Optic project from over the summer)

Created `Learning` category 

---

_data/tools.yml

Realized I miscategorized Swagger Inspector :) Fixed

Switched Swagger Insector -> SaaS

---

_data/categories.yml

Hi 
Thank you for this great resource!
This PR fixes a minor spelling mistake in the description of the DSL category's description

Fix minor spelling error in description of DSL category

---

_data/tools.yml

Hi,
I am the author of a testing tool for RESTful APIs called EvoMaster.
I added the entry for it under the `testing` category.
Let me know if there is any problem with it.
Many thanks
Andrea

Added entry to EvoMaster

---

_data/tools.yml

Added a Mock server tool: Open API Mocker

Added Open API Mocker mocking tool

---

_data/tools.yml

Update as requested by @philsturgeon

swagger2openapi also has a CLI

---

_data/tools.yml

Supermodel brings API -style and description-format agnostic, reusable data modeling. Finally we have added the support for OAS3 so you can model your resources using (real) JSON Schema and then use these models in OAS v2/v3 but also GraphQL or Avro schemas!
Note, I the categories did not feel right (I was thinking about misc vs. DSL), so I've created the "data modeling" category. 
Thanks!

Add supermodel.io

---

_data/tools.yml

[Unchase.OpenAPI.Connectedservice](https://github.com/unchase/Unchase.OpenAPI.Connectedservice) - is a Visual Studio 2017/2019 extension to generate C# (TypeScript) HttpClient (or C# Controllers) code for OpenAPI web service with [NSwag](https://github.com/RSuter/NSwag).

Add Unchase.OpenAPI.Connectedservice

---

index.html

Let's get into the meat quicker.

Get on with it

---

_data/tools.yml

Add [meeshkan](https://github.com/Meeshkan/meeshkan) tool under learnings and mock.

Add meeshkan

---

_data/tools.yml

I'm not from the NestJS team, but I use this module on prod.

Add official nestjs swagger module

---

.gitignore
_data/tools.yml

Added IBM's OpenAPI Validator tool as a Descripton Validator. 
Modified the .gitignore to ignore .jekyll-metadata from local testing

Added IBM's OpenAPI Validator tool

---

_data/tools.yml

an OpenAPI code generator for Spring Boot.

openapi-processor-spring

---

_data/tools.yml

https://cuelang.org/, https://cuelang.org/docs/integrations/openapi/ for the integration

CUE is a DSL and tool that can generate OAS3

---

_data/tools.yml

adding ApiBldr for gui-editors

adding ApiBldr

---

_data/tools.yml

updated links of openapi-processor-spring

updated openapi-processor links

---

_data/tools.yml

This tool had been tested against over 900 Open API definitions v2 and v3, through compiling the generated codes.

Added tool OpenApiClientGen

---

_data/tools.yml

Add JSON Designer visual JSON schema editor app for iOS

Add JSON Designer

---

_data/tools.yml

Signed-off-by: Rifa Achrinza <25147899+achrinza@users.noreply.github.com>

feat: adds LoopBack 4

---

_data/tools.yml

Hi! This is a little project of mine to generate OpenApi Description Documents by supplying request/response bodies.

Add InducOapi to learning tools

---

_data/tools.yml

Thank you for making this repository and making the community aware of the OpenAPI tooling. vREST NG is an Automated API Testing tool that allows adding OpenAPI Spec to generate API test cases, provide API coverage report, schema validation of API responses, etc.

Added vREST NG Link

---

_data/tools.yml

Add openapi-validator-bundle

---

_data/tools.yml

From openapi-dev-tool command-line interface, you can:
- design your OpenAPI specifications for several contexts of uses (without any copy-paste) ;
- write your OpenAPI specifications by using several files (to avoid having a unique large file unmaintainable) ;
- publish easily your OpenAPI files and reuse it to generate your client or your server ;
- view documentation in real-time ;
- etc.

Add openapi-dev-tool (https://github.com/lyra/openapi-dev-tool)

---

_data/tools.yml

My other PR's patch was deleted (I seem to have mixed a few repositories in the cleanup process). This is the right one. https://github.com/apisyouwonthate/openapi.tools/pull/219 can be closed.

Added OpenAPI3 Fuzzer

---

.gitignore

For example directory '.idea' created by IntelliJ Idea.

Ignore all hidden files

---

_data/tools.yml

Hi, here's a change to include OpenAPI snippets for visual studio code.

VSCode OpenAPI Snippets Extension

---

_data/tools.yml

Adding RestCase designer and RestCase docs tools

Adding RestCase designer and RestCase docs tools

---

_data/tools.yml

Adding an awesome tool that I recently discovered.

Add jekyll-openapi

---

_data/tools.yml

Adds https://www.django-rest-framework.org/api-guide/schemas/

add Django REST Framework

---

_data/tools.yml

Goa generates openapi v2 and v3 files from Go's DSL

📝 add Goa at DSL

---

_data/tools.yml

Add readyapi details

---

_data/tools.yml

Added openapi-snippet & openapi-snippet-cli to Parsers section.

Add openapi-snippet & openapi-snippet-cli

---

_data/tools.yml

Add description of Perl Validator JSONSchema::Validator

add description of JSONSchema::Validator validator

---

_data/tools.yml

Add new tool under security category

---

_data/tools.yml

adapted entry for OData OpenAPI

Update tools.yml - entry for OData OpenAPI

---

_data/tools.yml

Adding Mockintosh - OSS mocking tool for Cloud Native environments

Adding new tool - Mockintosh

---

_data/tools.yml

Also making small tweaks to the `link` and `description` fields :owl:
For reference, see this blog post: https://blog.readme.com/openapi-initiative-v3-1/

docs: ReadMe now supports OpenAPI v3.1

---

_data/tools.yml

Feels like this would belong more in security

OpenAPI3 Fuzzer -> category change

---

_data/tools.yml

I have added the JetBrains tools into gui-editors category.
The OpenAPI plugin is pretty helpful for API design.

Added JetBrains tools into gui-editors category.

---

_data/tools.yml

Updated RapiDocs homepage address as it has recently changed

Updated RapiDocs homepage address

---

_data/tools.yml

MkDocs Swagger UI Tag is a MkDocs plugin supports for add Swagger UI in page.

Add MkDocs Swagger UI Tag

---

_data/tools.yml

👋 Hi, I'd like to add a little Node.js project I'm working on that generates a command line tool from an OpenAPI spec.

Add OpenAPI Commander

---

_data/tools.yml

https://github.com/openclarity/apiclarity/pull/131

Add APIClarity back following OAS V3 support

---

_data/tools.yml

The worlds fastest OpenAPI linter and validator. Compatible with Spectral rule-sets and  designed for enterprise-grade speed and scale.
Signed-off-by: Dave Shanley <dave@quobix.com>

Added vacuum to the list of OpenAPI linters

---

_data/tools.yml

See https://github.com/p1c2u/openapi-spec-validator/pull/143 and https://github.com/p1c2u/openapi-core/pull/419

openapi-spec-validator and openapi-core support OpenAPI 3.1

---

_data/tools.yml

Updated openapi-format with OpenAPI 3.1 support & convert category.

Updated openapi-format with OpenAPI 3.1 support

---

_data/tools.yml

👋 Hello! Ran across your site this week and wanted to add a project I created. If this isn’t a good fit for the site, that’s fine. But if it is, happy to fix anything in this PR. Thanks for making this resource!

Add openapi-typescript

---

_data/tools.yml

I'm the creator of this project. Let me know if you have any questions.

Add Counterfact to the tools list

---

_data/tools.yml

A simple OpenAPI 3 comparison tool, written in C# and available as a NuGet package.
GitHub: https://github.com/criteo/openapi-comparator
Nuget: https://www.nuget.org/packages/Criteo.OpenApi.Comparator
Thanks!

Added C# OpenAPI Comparator: 

---

_data/tools.yml

Add entry for RESTler fuzzer.
Closes #261

Add entry for RESTler fuzzer.

---

_data/tools.yml

Merged Zuplo to one entry and added support for 3.0.

Fixing up Zuplo post OpenAPI launch

---

_data/tools.yml

And also corrected a link and description for `libopenapi`
Signed-off-by: Dave Shanley <dave@quobix.com>

Added openapi-changes to list

---

_data/tools.yml

- Updates ReadMe
- Updates `oas`
- Adds `oas-normalize`
- Adds `api`

Update ReadMe and refresh ReadMe OSS tools 🦉

---

_data/tools.yml

Language was wrong and the link changed

Update link to optic

---

_data/tools.yml

Hey there - I came across your site and have a project I've worked on to suggest. It's a tool that generates OpenAPI specifications from network requests. Thank you!
Demo: https://atyourservice.awalsh.io
Repo: https://github.com/AndrewWalsh/at-your-service
Resolves: #396

Add at-your-service

---

_data/tools.yml

Hi, this Ruby gem add improve test log for RSpec and WebMock,
validate its according to API Blueprint and Open API,
show the documentation coverage with log.
https://github.com/funbox/fitting for details

Add Fitting description

---

_data/tools.yml

Hot Potato is an OpenAPI conformance testing tool that I helped create with the former test automation team at Hyland Software. We were able to release it as open-source, and I provided the link to my fork which is being actively maintained.
Please let me know if you need any more information.

Added Hot Potato Reverse Proxy

---

_data/tools.yml

- updated openapi-processor
- added openapi-processor/openapi-parser

updated openapi-processor, added openapi-processor/openapi-parser

---

_data/tools.yml

Hi there,
I've been working on [OpenAPI HttpFoundation Testing](https://github.com/osteel/openapi-httpfoundation-testing) and would like to update its description as a result. The category is the same though!
Cheers,
Yannick

Updated description for OpenAPI HttpFoundation Testing

---

_data/tools.yml

Add `openapi-request-response-validation` to the Data Validators

Add openapi-request-response-validation

---

_data/tools.yml

Request to update Microcks language and description with thanks.

Update tools.yml for Microcks

---

_data/tools.yml

wiretap is the world’s sexiest API diagnostics tool. (self-proclaimed)
It's powered by `libopenapi` and facilitates compliance checking OpenAPI contracts against clients and servers. It does not require any code changes and operates transparently.
Docs: https://pb33f.io/wiretap/
Code: https://github.com/pb33f/wiretap

Added wiretap to the tools list.

---

_data/tools.yml

Added:
- openapi-schema-validator ( https://www.npmjs.com/package/@seriousme/openapi-schema-validator ) 
- fastify-openapi-glue ( https://www.npmjs.com/package/fastify-openapi-glue )
Kind regards,
Hans

Addition of openapi-schema-validator and fastify-openapi-glue to tools

---

_data/tools.yml

Fix APIMatic's naming, URLs, and category.

Review and fix APIMatic links.

---

_data/tools.yml

https://www.frogment.com/
Craft robust OpenAPI Specs Faster
A free openAPI spec editor and linter that breaks down your spec into fragments to make editing easier and more intuitive.

added frogment editor

---

_data/tools.yml

Fixes https://github.com/OAI/Tooling/issues/82

Add Traefik Hub

---

_data/categories.yml
_data/tools.yml

This PR adds a new tool that I use [Treblle](https://www.treblle.com/) as well as a new category for monitoring tools

New Tool and new category

---

_data/tools.yml

Bring your Swagger/OpenAPI Specification and get beautiful API References.
- 100% Open Source & Free ([github.com/scalar/scalar](https://github.com/scalar/scalar))
- A deeply integrated Rest API Client (Also Free & Open Source)
- Integrations with Vue.js, React, a CDN, Fastify and soon to be many more
- All CSS variables are editable so you can easily add your own typography & color palettes.
- Support for OpenAPI 3.1, OpenAPI 3.0, and Swagger 2.0
- Fully integrated Search (Using fuse.js)
- Free hosting with an https://apidocumentation.com/ subdomain
- Code samples to show off your API in most popular languages
- And More!

feat: add scalar api docs

---

_data/tools.yml
index.html

& update fern description and metadata

Tweak UTM parameters added to links

---

_data/tools.yml

Reverts apisyouwonthate/openapi.tools#471

Revert "Add Stainless to tools for SDK codegen"

---

_data/tools.yml

Adding the tool to the directory (not just a sponsor)

Adding ratemyopenapi

---

_data/tools.yml

- Add a new tool: `openapi-merge`;
- Update v3.1 support status for `swagger-parser`.

Add a tool and update v3_1 status for another tool.

---

_data/tools.yml

Adds the [Fuego](https://github.com/go-fuego/fuego) web framework

Adds Fuego API framework

---

_data/tools.yml

Add docuo to documentation category

---

CONTRIBUTING.md

@philsturgeon following our chat, let me know your thoughts on this and who else to involve. Raising this for open discussion.

docs: start conversation on contribution standards

---

_data/tools.yml

https://www.apitive.com appears to be dead.

Remove Apitive (defunct)

---

_data/tools.yml

feat: add TypeSpec (#515)

---

_data/tools.yml

Hi. Thanks for your project.
I have developed a TypeScript client generator ([apigen-ts](https://github.com/vladkens/apigen-ts)) and would like to add to the general list of tools related to OpenAPI.

new tool: apigen-ts

---

_data/tools.yml

Adding two tools:
- DevProxy built-in plugin OpenApiSpecGeneratorPlugin 
- mitmproxy2swagger

Add DevProxy-OpenApiSpecGeneratorPlugin and mitmproxy2swagger

---

_data/tools.yml

Update tools.yml with more recent connexion information

---

_data/tools.yml

Add OpenAPI Viewer.
Addresses 2/2 of https://github.com/apisyouwonthate/openapi.tools/issues/517.

feat: add OpenAPI Viewer (#517)

---

_data/tools.yml

Add OpenAPI Preview.
Addresses 1/2 of https://github.com/apisyouwonthate/openapi.tools/issues/517.

feat: add OpenAPI Preview (#517)

---

_data/tools.yml

Add server stubs
Change URL
Update languages to reflect latest functionality

Update Fern information

---

_data/tools.yml

Add Zudoku (https://zudoku.dev/) to Documentation section

Add Zudoku

---

_data/tools.yml

Flotiq supports the following schemes: v2, v3, v3.1

Flotiq: updated description support for schema

---

_data/tools.yml

This new framework automatically generates coherent OpenAPI 3.1 document and the relative server implementations from a formal definition of models and services in Typescript. The framework also handles all data validation both in input and output.

Add `mondrian-framework`

---

_data/tools.yml

- Added ts-oas which is a OpenAPI specifications generator:
[https://github.com/ts-oas/ts-oas](https://github.com/ts-oas/ts-oas)

Add ts-oas

---

_data/tools.yml

- APIMatic OpenAPI Linter - GitHub App (https://github.com/marketplace/apimatic-openapi-linter)
- APIMatic Documentation (https://docs.apimatic.io/validate-lint-apis/apimatic-github-app/github-app-overview/)

Added APIMatic GitHub App
