apisyouwonthate/openapi.tools

- _data/tools.yml
[OpenAPI Generator](https://github.com/OpenAPITools/openapi-generator) is a community-driven fork of swagger-codegen based on current v2 version `2.4.0-SNAPSHOT`. It is an alternative to swagger-codegen v3 to support OAS2 and OAS3. All generators have been migrated.
More than 40 top contributors and template creators of Swagger Codegen have joined OpenAPI Generator as the founding team members.
> Add openapi-generator

- _data/tools.yml
- added `link`
- put openapi-generator in more categories (sdk, converters)
> Put openapi-generator in more categories

- _data/tools.yml
Added a new entry for the [BigstickCarpet/swagger-parser library for Node.js](https://github.com/BigstickCarpet/swagger-parser).  I also updated the existing entry for [BigstickCarpet/swagger-cli](https://github.com/BigstickCarpet/swagger-cli) to indicate that it now supports OpenAPI 3.0
> Added new parser/validator Node.js library

- _data/tools.yml
APIMatic offers a Developer Experience Portal for Documentation and CodeGen as a SDK Generator. Support for both versions of OpenAPI is there. The list has been updated accordingly.
> Added APIMatic in Documentation and SDK Generator's section

- _data/tools.yml
Since the release v0.5.0 linter-swagger support OpenAPI 3.0.
See [issue#66](https://github.com/AtomLinter/linter-swagger/issues/66)
> Support linter-swagger OpenAPI3

- _data/tools.yml
Hey! I recently launched openapi3-generator, a tool to generate anything (docs, code, etc.) from an OpenAPI 3. I say "anything" because basically what it does is just pass an OpenAPI 3 document to a Handlebars template, and you can create your own templates.
https://github.com/fmvilas/openapi3-generator
> Add openapi3-generator

- _data/tools.yml
The linked issue for ReDoc to support v3 is closed. Updating the tools list to reflect this.
> ReDoc now supports V3

- index.html
I was on the page looking up a tool and notice the OAS version was behind
Changed 3.0.1 -> 3.0.2
> Update OAS version and link

- _data/tools.yml
Hey there, thanks for making/maintaining this list!
This adds [Assertible](https://assertible.com) to the Testing section in tools.yml. Please let me know if I can change or clarify anything. Assertible has no limits on importing OAI docs, only faster schedules and such require upgrades. Happy to clarify that in the yml if you want.
Actually, we just added support for importing JSONSchema's as assertions from OAIv3 documents and someone we were talking told us they look here for OAIv3 tools and thought Assertible would be a good fit :smiley: 
Thank you!
> Add Assertible to Testing section

- _data/tools.yml
Minor fix: Google Gnostic does indeed support v2 (sorry if it wasn't added for some other reason, just close this).
- https://github.com/googleapis/gnostic
- https://twitter.com/no_d_here/status/1055304603162439680
> Add v2 support to Gnostic

- _data/categories.yml
- _data/tools.yml
As discussed in #52, two new categories have been added and one was renamed. 
While I was checking the docs for each tool, I added **sway** and **kin-openapi** to the new *Data Validators* category. I have't tested them personally for this but from the docs it seems like they are able to do that.
Also looking trough docs for all the tools I found [p1c2u/openapi-core](https://github.com/p1c2u/openapi-core) which is a python library that also seems to have the ability to validate requests and responses. It might be valuable to add it as well or at least open an issue with them to see if they are interested.
> Split Parsers / Validators into 3 new categories

- _data/tools.yml
openapi-spec-validator supports both v2 and v3
> openapi-spec-validator has v2 support

- _data/tools.yml
Requested by @philsturgeon in Slack:
https://apisyouwonthate.slack.com/archives/C6EEULS87/p1541185349034200?thread_ts=1541086002.032400&cid=C6EEULS87
https://github.com/Dorthu/openapi3
Here are some snippets of the functionality from the README:
> A Python OpenAPI 3 Specification client and validator for Python 3.
> ...
> This module can be run against a spec file to validate it like so:
> ```
> python3 -m openapi /path/to/spec
> ```
> ...
> This library also functions as an interactive client for arbitrary OpenAPI 3 specs. For example, using Linode's OpenAPI 3 Specification for reference:
> ...
@Dorthu
> Add dorthu/openapi3 to parser tools

- _data/tools.yml
Modified the _data/tools.yml to include two NodeJS libraries:
- [openapi-enforcer](https://www.npmjs.com/package/openapi-enforcer)
- [openapi-enforcer-middleware](https://www.npmjs.com/package/openapi-enforcer-middleware)
> Add openapi-enforcer and openapi-enforcer-middleware

- _data/tools.yml
Mojolicious::Plugin::OpenApi is a great tool that allows you to use Swagger and OpenAPI with a Mojolicious Web Framework as an input for your server routes, also it provides automatic validation for requests and responses (optional) and generate documentation in html and json formats.
In my opinion, it's the best such tool in Perl world. So it would be nice to mention it in your project.
> Added Mojolicious::Plugin::OpenApi under server category

- _data/tools.yml
Initial support for OpenAPI v3 has been completed, as well as some support for Java.
> Updating guardrail definition

- _data/tools.yml
[Fakeit](https://github.com/justinfeng/fakeit) is a command line / docker tool to create mock server from Openapi specification
Description
* Randomly generated response
* Request validation
* Load specification from local or remote
* Support specification in yaml or json format
> Add Fakeit to mock server tools

- _data/tools.yml
[Chai OpenAPI Response Validator](https://github.com/openapi-chai/chai-openapi-response-validator) is a Chai plugin providing support for easily asserting that HTTP responses satisfy an OpenAPI spec, e.g.:
```
expect(res).to.have.status(200).and.satisfyApiSpec
```
Helps to do Contract Testing with OpenAPI in Node.js. (Related to your discussion on contract testing with JSON schema https://apisyouwonthate.com/blog/writing-documentation-via-contract-testing) 
Feedback appreciated! :)
> add Chai OpenAPI Response Validator

- _data/tools.yml
Fixed a copy/paste inflicted issue in the VSCode plugin name
> Fix VSCode plugin name

- _data/tools.yml
Unfortunately after adding this package (https://github.com/apisyouwonthate/openapi.tools/pull/112) I discovered that it was not ready for release, and so have taken it down for the time being. Hopefully we can re-release a new and improved version soon!
> remove chai-openapi-res-validator

- _data/tools.yml
openapi-cli-tool is a collection of useful commands for working with OpenApi specifications. 
Description:
- Can list up defined API paths.
- Display an API specification which is resolved ($ref).
- Bundle multi-file into one (output to json|yaml|html).
- OAS interactive scaffolding.
> Add openapi-cli-tool

- _data/tools.yml
A python developer can generate OpenAPI 3.0 spec file easily using this library.
It consumes a `response` object and converts it into OpenAPI spec. A developer can create the entire documentation of the entire app within one reproducible script.
> Adding new Python tool that generates OpenAPI3.0 specs

- _data/tools.yml
At the moment, [`tsoa`](https://github.com/lukeautry/tsoa) is the most used TypeScript library for OpenAPI and Swagger generation + validation (based off of metrics from npmtrends.com). I noticed that it is isn't available in https://https://openapi.tools/ so I've created this PR to add it. I apologize if I was supposed to create an issue first, but I didn't see a CONTRIBUTING.md file so I wasn't sure what the process was. Hopefully you can accept this PR. Thank you. :)
> adds tsoa to the list of server implementations

- _data/tools.yml
Generate OAS Specs by running your API Tests. The traffic from the tests is used to generate accurate specs.
> Added Generate OAS

- _data/tools.yml
Add oas3-api-snippet-enricher to list of documentation tools. The tool automatically includes code samples for all methods in the API.
> Add oas3-api-snippet-enricher mention

- _data/tools.yml
We knocked our documentation renderer into a shape where it's useful by itself so that others can use it, either alone or in a Rails app. Adding it to the list in case anyone comes here looking for such a thing.
> Add nexmo-oas-renderer gem to documentation section

- _data/tools.yml
Restful-react provides a consistent, declarative way for React apps to interact with RESTful backends, featuring code-generation from OpenAPI descriptions.
> Add restful-react

- _data/tools.yml
Hi! 
Just wanted to add our project to your awesome list! Thanks!
> Add OpenAPI Style Validator to the list of available tool

- _data/tools.yml
Hello :wave:, I'm adding a link to the OpenAPI 3 Parser I maintain. It's a long running project however I didn't know about this resource before.
I've also got a blog post that might be of interest but didn't seem to fit any categories: https://kevindew.me/post/188611423231/how-to-write-an-openapi-3-parser
Thanks
> Add Ruby openapi3_parser gem

- _data/tools.yml
Fixed OpenAPI Mocker and other tools, based on the issue received in https://github.com/jormaechea/open-api-mocker/issues/2
> OpenAPI specification naming fixed in every tool

- _data/tools.yml
Hi All, I'd like to submit our headless Content Management System - [Flotiq](https://flotiq.com) - to the list. 
The tool provides:
1. a GUI editor for defining Content Types, which are based on OpenAPI primitives
2. an automatically updated API-doc, with built-in code samples, generated after every change to the Content Types
3. Downloadable SDKs and Postman collection, regenerated automatically with every change to the Content types
Please let me know if there's anything you'd like me to amend in this PR.
> Add Flotiq mention to SDK, GUI editors and misc

- _data/tools.yml
[Chai OpenAPI Response Validator](https://github.com/RuntimeTools/OpenAPIValidators/tree/master/packages/chai-openapi-response-validator) was added in https://github.com/apisyouwonthate/openapi.tools/pull/130. 
This PR updates the GitHub link, which has changed because I've since converted that repo to a monorepo (to group it with its sister package [`jest-openapi`](https://github.com/apisyouwonthate/openapi.tools/pull/193))
Thanks!
> update GitHub link to chai-openapi-response-validator

- _data/tools.yml
[jest-openapi](https://github.com/RuntimeTools/OpenAPIValidators/tree/master/packages/jest-openapi) is a sister package to [Chai OpenAPI Response Validator](https://github.com/RuntimeTools/OpenAPIValidators/tree/master/packages/chai-openapi-response-validator), which you already have listed here. 
jest-openapi provides Jest matchers to easily assert that HTTP responses satisfy an OpenAPI spec, e.g.:
```
expect(responseObject).toSatisfyApiSpec();
```
Helps to do Contract Testing with OpenAPI in Node.js.
Feedback appreciated! :)
> add jest-openapi

- _data/tools.yml
This library allows users to quickly generate an OpenAPI definition document based on a given JSON response.
> Add response2schema to Learning tools

- _data/tools.yml
The goal of this library is to create *at runtime* a client helper to make and validate calls to an OpenAPIv3-compliant backend. It is used by [ToucanToco](https://toucantoco.com), in [a POC for the "contract-driven API pattern"](https://github.com/ninofiliu/contract-driven-api), and also in my upcoming personal website. Would be awesome to appear in openapi.tools!
Since it's a runtime library, it *does not* generate code, so it's not really an SDK generator, eventhough the usage of it is *very* close (but a bit better imho, lol), which is why I put the category halfway between sdk and miscellaneous.
Thanks for reviewing this! :bow:
> Add tool: oa-client

- _data/tools.yml
This adds the [Restish](https://rest.sh/) CLI tool, which didn't fit perfectly in any single category so I put it into several:
- Documentation: It will read OpenAPI and generate useful `--help` which includes the request/response schemas & descriptions as well as generated example commands you can make against the API.
- Miscellaneous: best place for a generic CLI tool?
- Testing: it can be used to make authenticated test requests against the API and filter the responses to specific fields you want to test.
> feat: add Restish

- _data/tools.yml
Spectral support was added to GitHub's super-linter (github/super-linter#286).
> Add super-linter

- _data/tools.yml
I'm just adding a slightly more modern openapi validator for Atom to the list 👍
> add Atom/linter-openapi to tools

- _data/tools.yml
Hey there,
It's a package to validate HttpFoundation (Symfony, Laravel, Drupal...) responses against OpenAPI definitions, meant to be used with integration tests.
I think `data-validators` is the right category here, but I might  be wrong.
Let me know what you think!
Cheers,
Yannick
> Add OpenAPI HttpFoundation Testing

- _data/tools.yml
APIFUzzer entry was not a valid yaml entry due to indentation errors. You may want to implement a github action that checks via a yaml.readfile if the modified file is indeed valid.
> Invalid yaml

- _data/tools.yml
Addition of a handy CLI/module to strip/filter OpenAPI specs via CLI/module.
Most common use-case is to remove internal/private paths.
Very practical for CI/CD pipeline operations.
> Add openapi-filter

- _data/tools.yml
Added the tool `openapi-format `,  which is a CLI to format an OpenAPI document by ordering fields in a hierarchical order, with the option to filter out flags, tags, methods, operationID's.
> Added openapi-format

- _data/tools.yml
Microcks supports importing OpenAPI 3.1 specifications for creating mocks and validating endpoints.
> Adding 3.1 support for Microcks + testing category

- _data/tools.yml
Hey, there!
My package is very tiny right now comparing to other PHP solutions, but still might be useful. I have another two packages related to OAS development, but they makes no sense if you won't approve this core package.
[openapi-data-mocker](https://github.com/ybelenko/openapi-data-mocker) was originally developed as part of [OpenAPI Generator - Server Slim 4](https://openapi-generator.tech/docs/generators/php-slim4) codegen. Then I realized that this tiny library maybe more useful as standalone package.
The major disadvantage that it cannot parse description document. So it expects deserialized parts description document in most of the methods, but I'm going to fix it in next versions.
The second issue is that it needs generated PHP models for referenced schemas.
Both confusing …
> Add openapi-data-mocker PHP package

- _data/tools.yml
I've spent a few days of documenting OAuth2 token endpoints with OAS3. Hope somebody might find it useful.
> Add oauth2_as_oas3_components repo

- _data/tools.yml
Added Portman from Apideck, which is a CLI to port an OpenAPI Spec to a Postman Collection, with contract & variation tests included.
> Add Portman, an OpenAPI to Postman convert tool for contract & variation testing

- _data/tools.yml
Mayhem for API is a fuzz-testing solution for APIs described by an OpenAPI specification.
> Add a tools link to Mayhem for API

- _data/tools.yml
OAS 3.1 support added to openapi-backend from 4.2.0
Issue tracking this feature: https://github.com/anttiviljami/openapi-backend/issues/158
> OpenAPI 3.1 supported with openapi-backend

- _data/tools.yml
Removed duplicate key for Rhosys/openapi-data-validator.js to allow for easy parsing of data to pull into OpenAPI tooling repository
> fix: Removed duplicate github key from Rhosys/openapi-data-validator.js

- _data/tools.yml
Bump supports most of the new features of OAS 3.1 (cf
https://bump.sh/blog/changes-in-openapi-3-1)
> data: Bump.sh has support for OAS 3.1 since the beginning of 2021

- _data/tools.yml
Added LucyBot api-spec-converter which can convert
between many different API definitions.
Supported formats:
* swagger_1
* swagger_2
* openapi_3
* api_blueprint
* io_docs
* google
* raml
* wadl
> LucyBot api-spec-converter

- _data/tools.yml
A sophisticated Kotlin code generation library capable of generating Jackson-annotated data classes, Spring Controller interfaces, and fault-tolerant OkHttp clients. Written in Kotlin, this library programatically generates code and is capable of handling advanced OpenApi3 specification features such as polymorphism.
https://github.com/cjbooms/fabrikt
> Adds a link to Kotkin Code generator: FabriKt. 

- _data/tools.yml
I assume openapi-explorer doesn't support OpenAPI 3.1 (yet) because this issue is still open and unresponded: https://github.com/Rhosys/openapi-explorer/issues/50
> openapi-explorer does not support OpenAPI v3.1

- _data/tools.yml
Mayhem for API added OAS3.1 support in version 2.10.0. Release notes: https://mayhem4api.forallsecure.com/docs/release-notes.html
> update to show OAS 3.1 support in mayhem for api

- _data/tools.yml
kotlin-openapi3-dsl is a DSL written in Kotlin to write OpenAPI descriptions in plain Kotlin.
> Add kotlin-openapi3-dsl

- _data/tools.yml
This reverts commit d158914abfd0631cd42326370defd1e2a2db42de. #335 rhosys/openapi-explorer#50
> Revert "openapi-explorer does not support OpenAPI v3.1 (#335)"

- _data/tools.yml
I recently rewrote the json-schema-to-openapi and openapi-to-json-schema tools in typescript, so those should be natively supported, and I also published a much more mature and correct version of `har-to-openapi`. This adds both of those.
> Added modern versin of har-to-openapi and changed language of openapi-contrib tools

- _data/tools.yml
👋  we now support 3.1! We also released our own diff tool [`optic diff` ](https://www.useoptic.com/docs/openapi-diff) which is a seperate toolchain from the rest of Opitc. 
Let me know if there's anything I can do to make this clearer :)
> Updated v3_1 for optic, added optic diff

- _data/tools.yml
endpoints spelled as "endpoins"
> Spelling mistake

- _data/tools.yml
This product appears to be defunct: the homepage listed just shows a 404 message, and other links I've found are either the same, or sub-domains with invalid certificates.
> Remove "RepreZen API Studio"

- _data/tools.yml
Enterprise grade, fully featured OpenAPI 3.1, 3.0 and Swagger parser for go. A complete toolset for reading and parsing OpenAPI and Swagger specifications. Comes complete with high and low-level APIs, diff engine, index and resolver.
Signed-off-by: Dave Shanley <dave@quobix.com>
> Added libopenapi to list of parsers

- _data/tools.yml
* Added the ".sh" extension as per current branding normalization efforts
* Added GitHub link to Open Source CLI
* Updated description
> Bump.sh description and branding update

- _data/tools.yml
Added Redocly OpenAPI VS code extension to Text Editors
marketplace: https://marketplace.visualstudio.com/items?itemName=Redocly.openapi-vs-code
github: https://github.com/Redocly/redocly-vs-code
> Added Redocly OpenAPI VS code extension to Text Editors

- _data/tools.yml
I noticed that Redocly had renamed some things without updating here, so this PR fixes the things I spotted.
> Update Redocly project names

- _data/tools.yml
As discussed over here: https://github.com/postmanlabs/openapi-to-postman/issues/499#issuecomment-1369204949, raising PR with v2 and v3.1 support marked as true.
> Updated version support for openapi-to-postman tooling.

- _data/tools.yml
I would like to add a tool from readme.io that now supports OpenAPI 3 according to https://github.com/readmeio/swagger-inline/issues/8 even though it does not mention it on [the website](https://openap.is).
> Add readmeio/oas

- _data/tools.yml
Adds sdk tool; Openapi Json Schema Generator
It generates python clients and is at https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
This generator works with 3.0.0 to 3.0.3 spec documents and 3.1.0 featured are being worked on. 
Could this PR be reviewed to get it added?
Thank you!
> Adds sdk tool; Openapi Json Schema Generator

- _data/tools.yml
The up-to-date information on `readmeio/oas` was added in https://github.com/apisyouwonthate/openapi.tools/pull/410, so we can safely revert https://github.com/apisyouwonthate/openapi.tools/pull/351, which is outdated. `oas` is no longer a CLI and it does indeed support OpenAPI v3.1.
> Remove outdated/duplicated `readmeio/oas` listing

- _data/tools.yml
See related release from Dec 2022: https://github.com/danielgtaylor/restish/releases/tag/v0.15.0
> fix: Restish supports Open API 3.1

- _data/tools.yml
Swagger UI v5.0.0 already supports OpenAPI v3.1.0
https://github.com/swagger-api/swagger-ui/releases/tag/v5.0.0 https://blueswen.github.io/mkdocs-swagger-ui-tag/demo/openapi-v3.1/
> Update MkDocs Swagger UI Tag information

- index.html
> Fix 404 error on broken favicon link

- _data/tools.yml
Release [v2.1.0](https://github.com/TheWall89/inducoapi/releases/tag/v2.1.0) of InducoApi now supports OpenApi Spec 3.1.0
> InducoApi v2.1.0 supports OpenApi 3.1.0

- _data/tools.yml
1. [api-smart-diff](https://github.com/udamir/api-smart-diff) - Compare two Json based API documents (OpenAPI, AsyncAPI, JsonSchema, GraphAPI)
2. [api-diff-viewer](https://github.com/udamir/api-diff-viewer) - React component to view the difference between two Json based API documents. Supported specifications: JsonSchema, OpenAPI 3.x, AsyncAPI 2.x.
3. [allof-merge](https://github.com/udamir/allof-merge) - Simplify your JsonSchema by combining allOf safely (OpenAPI, JsonSchema)
4. [api-ref-bundler](https://github.com/udamir/api-ref-bundler) - Bundle all external $ref in Json based API document into single document (OpenAPI, AsyncAPI, JsonSchema)
> Add new tools

- _data/tools.yml
Request to add [`go-openapi-spec-code-diffs`](https://github.com/RHEcosystemAppEng/go-openapi-spec-code-diffs) tool. 
A golang validation tool that compares given OpenAPI specs (e.g. openapi.yaml) vis-a-vis routes (e.g. /api/v1/customer/:id) defined in golang source code and reports differences. This is useful in scenarios where you want to keep the OpenAPI specs and Code in synch.
> Add go-openapi-spec-code-diffs tool to the list

- _data/tools.yml
Request to update the category for go-openapi-spec-code-diffs tool, so that it can appear under `Miscellaneous` category. Thanks.
> Update category for go-openapi-spec-code-diffs

- Gemfile.lock
I encountered an issue while trying to install dependencies with ruby 3.2. Following this thread solved the issue https://github.com/github/pages-gem/issues/859
Liquid 4.0.4 is compatible with Ruby 3.2
> bump liquid to 4.0.4

- _data/tools.yml
There aren't many tools in the Go ecosystem that tackle the needs of OAS generation/parsing. 
This tool is an alternative to outdated Swagger2.0 `go-swagger`.
> :rocket: Added a new tool - go-oas/docs

- _data/tools.yml
Updates openapi json schema generator
v3.1.0 documents are now supported per: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator/releases/tag/3.1.0
> Updates openapi json schema generator, 3.1.0 now supported

- _data/tools.yml
Hello, we are transferring the fitting repository and would like to update the information
> Change link and github for fitting library

- _data/tools.yml
This change adds [Huma](https://huma.rocks/) to the list of OpenAPI tools.
> feat: add Huma to tools

- _data/tools.yml
APITree website is not reachable and the Github repo is empty.
> fix: remove APITree

- _data/tools.yml
Counterfact now supports OpenAPI v2. Also placed in the correct categories (it's primarily a mock server) and updated the description.
> Update description and categorization for Counterfact

- _data/tools.yml
Add Apple's Swift OpenAPI Generator to the list of client and server code generators.
> Add Swift OpenAPI Generator

- _data/tools.yml
Hi. This adds https://github.com/ahx/openapi_first.
I am planning on adding converters (DateTime etc) and maybe test integration, but currently this thing does what is described here. Thanks for maintaining this list.
> Add openapi_first Ruby gem

- _data/tools.yml
> Fix link to Prism homepage in tools.yml

- _data/tools.yml
Mocklab no longer exists and is now WireMock Cloud. This PR updates  the Mocklab entry to reference Wiremock Cloud and update the categories and OpenAPI versions based on the newest Wiremock Cloud features
> Mocklab is now Wiremock Cloud

- _data/tools.yml
readmeio/oas-normalize was archived in GitHub on 20231005, and points to the new repo location readmeio/oas
> Update oas-normalize repo location

- _data/tools.yml
Hi,
The PR is to update the support list of `openapi-dev-tool` which supports OAS 2, 3, 3.1 for now.
Regards,
> openapi-dev-tool support OAS 2, 3, 3.1

- _data/tools.yml
Openapi json schema generator now supports Python and Java
per this release:
https://github.com/openapi-json-schema-tools/openapi-json-schema-generator/releases/tag/4.2.0
> Updates languages supported by Openapi json schema generator

- _data/tools.yml
**Proposal**
Add OpenAPI Qraft to the `code-generators` and `sdk` _category_.
**Reason**
An actively developing React API Client generator with real users.
**Impact**
More satisfied React developers.
> feat(sdk): add OpenAPI Qraft as an SDK generation tool for React

- _data/tools.yml
A MkDocs plugin supports adding [Redoc](https://github.com/Redocly/redoc) to the page.
> Add MkDocs Redoc Tag

- _data/tools.yml
I moved the tool to the php-openapi org on github, so it has a new URL.
https://github.com/php-openapi/yii2-app-api
> Change URL for yii2-app-api

- _data/tools.yml
API-Fiddle is an opinionated API design tool built for collaboration and exploration. It is built around OpenAPI and supports it's users in quickly creating API definitions for technical documents, meetings, and reviews.
> Add api-fiddle

- _data/tools.yml
Adding [django-contract-tester](https://github.com/maticardenas/django-contract-tester), it's a django-exclusive tool which allows to validate [DRF](https://github.com/encode/django-rest-framework) and [Django-Ninja](https://github.com/vitalik/django-ninja) APIs against their OpenAPI specification.
One of its most useful use cases is to allow you to simply replace the [test client](https://github.com/maticardenas/django-contract-tester?tab=readme-ov-file#django-testing-client) and have all your tests performing contract validation.
> feat: add django-contract-tester

- _data/tools.yml
The IBM OpenAPI Validator officially supports OpenAPI 3.1 - noting that in the data. Thanks!
> docs: note 3.1 support for ibm validator

- _data/tools.yml
Scramble is OpenAPI documentation generator for Laravel. It generates API documentation for projects automatically without requiring a developer to manually write PHPDoc annotations.
https://scramble.dedoc.co
> Added Scramble documentation generator

- _data/tools.yml
Alphadoc services have been shut down on 16 August 2024.
> Remove Alphadoc

- _data/tools.yml
[@hey-api/openapi-ts](https://github.com/hey-api/openapi-ts) is a successor to [openapi-typescript-codegen](https://github.com/ferdikoomen/openapi-typescript-codegen). It currently offers OpenAPI to TypeScript codegen functionality and some people use it for publishing their own SDKs. More features will be added as time goes on. Thank you for considering adding this project to OpenAPI tools!
> Add Hey API

- _data/tools.yml
Adds [Framna Docs](https://github.com/shapehq/framna-docs/), a tool we've built at [Shape](https://shape.dk) (soon to be [Framna](https://framna.com)) to centralize documentation and support teams in spec-driven development.
Our description documents reside in GitHub repositories, allowing teams to easily review changes. This also enables fine-grained access control, as Framna Docs uses GitHub-based authentication to display only documentation from repositories that users have access to.
Framna Docs displays documentation on any branch and tag in any repository users have access to on GitHub and enables them to choose their preferred viewer from Swagger UI, Stoplight Elements, and Redocly.
> Adds Framna Docs

- _data/tools.yml
[Rage](https://github.com/rage-rb/rage) is a Ruby web framework for building APIs with first-class OpenAPI support.
> Add rage-rb

- _data/tools.yml
Since release 5.4.0 https://github.com/cdimascio/express-openapi-validator/releases/tag/v5.4.0 express-openapi-validator supports OpenAPi version 3.1. This PR introduces this change to the table
> Adds support for version 3.1 in express-openapi-validator

- _data/tools.yml
Adding oas-patch tool to the list
A command-line tool for OpenAPI Overlays, allowing you to patch and modify OpenAPI documents. And create overlays from two openapi documents
> Add oas-patch

- _data/tools.yml
Add drf-spectacular: https://github.com/tfranzel/drf-spectacular
> Add drf-spectacular

- _data/tools.yml
JanePHP is a monorepo, which holds the SDKs for multiple open api versions.
The original link is a project which has been deprecated, and may cause users to think JanePHP is no longer maintained.
> Update JanePHP link
